name: Orchestrator
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  create-tag:
    permissions: write-all
    uses: ./.github/workflows/create-tag.yaml
    secrets: inherit

  deploy-api:
    needs: create-tag
    uses: ./.github/workflows/deploy-api.yaml
    secrets: inherit
    with:
      tag: ${{ needs.create-tag.outputs.tag }}

  deploy-jobs:
    needs: create-tag
    uses: ./.github/workflows/deploy-jobs.yaml
    secrets: inherit
    with:
      tag: ${{ needs.create-tag.outputs.tag }}
